/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "on-secondary-fixed-variant": "#7c4100",
          "primary-container": "#ff766b",
          "tertiary-fixed": "#ff909b",
          "secondary-fixed-dim": "#ffb375",
          "on-surface-variant": "#adaaaa",
          "secondary-dim": "#ed8200",
          "secondary-fixed": "#ffc69a",
          "secondary": "#fd8b00",
          "surface-container-lowest": "#000000",
          "on-tertiary-fixed": "#39000c",
          "primary-dim": "#e51a22",
          "on-secondary": "#442100",
          "inverse-on-surface": "#565555",
          "surface-container-low": "#131313",
          "outline-variant": "#484847",
          "tertiary-dim": "#e7004c",
          "on-surface": "#ffffff",
          "tertiary-fixed-dim": "#ff7989",
          "on-background": "#ffffff",
          "primary-fixed-dim": "#ff5b51",
          "outline": "#767575",
          "primary": "#ff8e83",
          "on-primary-fixed": "#000000",
          "inverse-primary": "#c10014",
          "primary-fixed": "#ff766b",
          "on-tertiary-container": "#000000",
          "tertiary-container": "#ff0355",
          "surface-variant": "#262626",
          "on-error": "#490013",
          "error-dim": "#d73357",
          "surface-bright": "#2c2c2c",
          "on-secondary-container": "#fff6f1",
          "on-tertiary-fixed-variant": "#780023",
          "surface-dim": "#0e0e0e",
          "secondary-container": "#904d00",
          "surface-tint": "#ff8e83",
          "surface-container-highest": "#262626",
          "surface-container": "#1a1919",
          "on-primary-container": "#4f0003",
          "surface-container-high": "#201f1f",
          "error": "#ff6e84",
          "on-error-container": "#ffb2b9",
          "error-container": "#a70138",
          "inverse-surface": "#fcf9f8",
          "on-secondary-fixed": "#532a00",
          "on-tertiary": "#490012",
          "surface": "#0e0e0e",
          "on-primary-fixed-variant": "#600005",
          "background": "#0e0e0e",
          "tertiary": "#ff6e81",
          "on-primary": "#650006"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "fontFamily": {
          "headline": ["Space Grotesk", "sans-serif"],
          "body": ["Inter", "sans-serif"],
          "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
